pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:checkstore/checkstore-devs.git
          - cd teste-checkstore-devs.git
          - git push --mirror git@github.com:iasminln/teste-checkstore-devs.git